version: '3'
services:
  app:
    depends_on:
      - mysql
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    image: recipe-mgmt-app
    container_name: recipe-mgmt-container
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8081:9000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=recipe_app
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
  mysql:
    image: mysql:5.7
    container_name: recipe-mgmt-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: recipe_app
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data: